### ISSUE TITLE
Changes to API...

### ISSUE THREAD

**Issue by tgrushka** [mconfalonieri/external-dns-hetzner-webhook#16]
that, alas, once again, kubernetes-sigs didn't tell us about. (What a drag, a 15-minute setup winds up taking 2-3 hours because Google thinks Apache and GPL licenses are not compatible, strips Hetzner for political rather than technical reasons, then makes us all invent external webhooks, then changes the API again.) But I must say... ONLY 2-3 hours, thanks to your webhook plugin, which probably took a lot longer to fork/customize.

So... THANK YOU!!!

It appears the helm chart values changed, with no notice to us, but I do like this API better than having to deal with sidecars. I haven't fully tested it yet, but all pods/healthchecks appear to be running.

I am visually impaired, hence the 4-space indents, that I also wish Google et. al. would support in general.

The takeaway is that your default for `WEBHOOK_HOST` of localhost no longer works, because external-dns now automatically assigns a random internal IP. Please test/update docs if you can.

```yaml
namespace: external-dns

domainFilters:
    -   my.example

policy: sync

provider:
    name: webhook
    webhook:
        image:
            repository: ghcr.io/mconfalonieri/external-dns-hetzner-webhook
            tag: v0.6.0
        env:
            -   name: WEBHOOK_HOST
                value: 0.0.0.0
            -   name: HETZNER_API_KEY
                valueFrom:
                    secretKeyRef:
                        name: hetzner-dns-token
                        key: HETZNER_DNS_TOKEN
```

**Comment by mconfalonieri** [comment]
Thank you for creating this issue, I will check the changes in external-dns!

I really wish there were a newsletter for this kind of changes on kubernetes-sigs side.

The problem with setting WEBHOOK_HOST to 0.0.0.0 is that the webhook API could potentially be used by malicious actors, as it will listen for connections on addresses reachable outside the pod (unless there is added security).

I will check this ASAP.

**Comment by mconfalonieri** [comment]
The issue seems to be relative to the `external-dns/external-dns` chart,  not in the `bitnami/external-dns` one that I used in my deployment. Is it correct @tgrushka?

I will add a section for the `external-dns/external-dns` one in the documentation.

**Comment by mconfalonieri** [comment]
I used this configuration and it works without changing the webhook address:

```yaml
namespace: external-dns

domainFilters:
    -   my.example

policy: sync

provider:
    name: webhook
    webhook:
        image:
            repository: ghcr.io/mconfalonieri/external-dns-hetzner-webhook
            tag: v0.6.0
        env:
            -   name: WEBHOOK_HOST
                value: 0.0.0.0
            -   name: HETZNER_API_KEY
                valueFrom:
                    secretKeyRef:
                        name: hetzner-dns-token
                        key: HETZNER_DNS_TOKEN
        livenessProbe:
            httpGet:
                path: /health
                port: http-wh-metrics
            initialDelaySeconds: 10
            timeoutSeconds: 5
        readinessProbe:
            httpGet:
                path: /ready
                port: http-wh-metrics
            initialDelaySeconds: 10
            timeoutSeconds: 5
```
