### ISSUE TITLE
Domain filtering returns error

### ISSUE THREAD

**Issue by coveraver** [mconfalonieri/external-dns-hetzner-webhook#32]
Thank you for this webhook.
I get errors adding txt records if I set the variable
```
      - name: DOMAIN_FILTER
        value: "sub.my-domain.com"
```

errors below:

```
time="2025-04-18T10:10:13Z" level=warning msg="Creating new target" dnsName=reg-grafana.test.my-domain.com recordType=TXT target="\"heritage=external-dns,external-dns/owner=default,external-dns/resource=ingress/metrics/grafana\"" ttl=default zoneName=my-zone-name
time="2025-04-18T10:10:13Z" level=warning msg="Creating new target" dnsName=reg-a-grafana.test.my-domain.com recordType=TXT target="\"heritage=external-dns,external-dns/owner=default,external-dns/resource=ingress/metrics/grafana\"" ttl=default zoneName=my-zone-name

time="2025-04-18T10:10:13Z" level=debug msg="Creating domain record" dnsName=grafana.test domain=my-domain.com recordType=A ttl=60 value=<IP> zoneID=my-zone-id
time="2025-04-18T10:10:13Z" level=error msg="Failed to do run once: soft error\nfailed to apply changes with code 500"
time="2025-04-18T10:10:13Z" level=error msg="Failed to Apply Changes: hetzner-dns: server responded with status code 422"
```

If you don't specify the variable, everything works.

**Comment by mconfalonieri** [comment]
Hi @coveraver, thank you!

From what I can see, apart from the 422/500 error, I see that there is an attempt to create a record on the subdomain `test.my-domain.com` despite the filter should allow only `sub.my-domain.com`, is it correct?

**Comment by coveraver** [comment]
Hi @mconfalonieri, thanks for your reply!
Sorry for the confusion(
My filter is
```
- name: DOMAIN_FILTER
  value: "test.my-domain.com"
```

And ingress creates subdomains for test.my-domain.com:
first.test.my-domain.com, second.test.my-domain.com and so on.
I need to cover `*.test.my-domain.com` and `test.my-domain.com` as well

**Comment by mconfalonieri** [comment]
Unfortunately I don't have  a  subdomain to test, but I tried to reproduce the  bug on my local environment in unit tests.  The only way I could reproduce this behavior:

```
time="2025-04-18T10:10:13Z" level=debug msg="Creating domain record" dnsName=grafana.test domain=my-domain.com recordType=A ttl=60 value=<IP> zoneID=my-zone-id
```

was by passing the zone information of `my-domain.com` instead of `test.my-domain.com`. I see that the domain is incorrectly set to my-domain.com in fact. Can you confirm if - when running without filter - the correct third-level domain zone ID (ID of test.my-domain.com) is passed while when you set the filter the second-level domain one (ID of my-domain.com) is passed?

**Comment by coveraver** [comment]
without filter
```
level=debug msg="Creating domain record" dnsName=example.test domain=my-domain.com recordType=A ttl=60 value=<IP> zoneID=<zone_id>
level=info msg="Creating record [example.test] of type [A] with value [IP] in zone [my-domain.com]"
```
with filter
```
level=debug msg="Creating domain record" dnsName=example.test domain=my-domain.com recordType=A ttl=60 value=<IP> zoneID=<zone_id>
level=info msg="Creating record [example.test] of type [A] with value [IP] in zone [my-domain.com]"
```
my full `values.yaml` just in case
```
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

tolerations:
- key: node-group
  value: qa
  operator: Equal

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-group
          operator: In
          values:
          - qa

domainFilters:
  - test.my-domain.com

dryRun: "true"
logLevel: debug
interval: "1m"

policy: upsert-only

provider: webhook

txtPrefix: wake-
txtOwnerId: wake-k8s

extraArgs:
  webhook-provider-url: http://localhost:8888

sidecars:
  - name: hetzner-webhook
    image: ghcr.io/mconfalonieri/external-dns-hetzner-webhook:v0.7.0
    ports:
      - containerPort: 8888
        name: webhook
      - containerPort: 8080
        name: http-wh-metrics
    livenessProbe:
      httpGet:
        path: /health
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /ready
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
      - name: HETZNER_API_KEY
        valueFrom:
          secretKeyRef:
            name: hetzner-credentials
            key: api-key
      - name: DRY_RUN
        value: "true"
      - name: HETZNER_DEBUG
        value: "true"
      - name: DOMAIN_FILTER
        value: "test.my-domain.com"
```
