### ISSUE TITLE
Readiness & Liveness probe errored

### ISSUE THREAD

**Issue by Haves1001** [mconfalonieri/external-dns-hetzner-webhook#33]
I've deployed external dns with the hetzner webhook:

````
sources:
  - ingress
  - service
  - traefik-proxy
domainFilters:
  - example.de
logLevel: info
txtOwnerId: example
logLevel: debug
namespace: external-dns
policy: sync


provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/mconfalonieri/external-dns-hetzner-webhook
      tag: v0.7.0
    env:
      - name: HETZNER_API_KEY
        valueFrom:
          secretKeyRef:
            name: hetzner-credentials
            key: api-key
      - name: DEFAULT_TTL
        value: "300"
    livenessProbe:
      httpGet:
        path: /health
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /ready
        port: http-wh-metrics
      initialDelaySeconds: 10
      timeoutSeconds: 5
extraArgs:
  - "--txt-prefix=reg-%{record_type}-"
  - "--traefik-disable-legacy"
````

But for some reason the pod is always unhealthy and I see the following errors:
````
Warning | Unhealthy | kubelet | Readiness probe errored: strconv.Atoi: parsing "http-wh-metrics": invalid syntax | 2 minutes (13 times over 4 minutes)
Warning | Unhealthy | kubelet | Liveness probe errored: strconv.Atoi: parsing "http-wh-metrics": invalid syntax | 2 minutes (12 times over 3 minutes)
````

I've tried out a lot of different configurations, but were not able to fix it, could you help me and take a look at the issue? 

Thanks you for the great plugin though!
